name: Migrate D1 Database

on:
  workflow_dispatch:
  push:
      branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NO_D1_WARNING: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm migrate:apply
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
